name: Run Superpages action

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Show current working directory and list docs/_posts
        run: |
          pwd
          ls -l docs/_posts

      - name: Run app/__main__.py with API_KEY from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python app/__main__.py

      - name: Commit and push changes in docs/_posts if any
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add docs/_posts
          if ! git diff --cached --quiet; then
            git commit -m "Update posts in Superpages"
            git push
          else
            echo "No changes to commit"
          fi
